### ISSUE TITLE
Code just hangs...

### ISSUE THREAD

**Issue by jd327** [yetzt/node-geocluster#1]
Am I doing something wrong?

``` javascript
var a = geocluster([
    [40.703312, -73.979683],
    [38.790787, -122.409561]
], 1.5);
console.log(a);
```

**Comment by yetzt** [comment]
two points seems to be too little to find clusters.

**Comment by yetzt** [comment]
well, with two elements, stddev is 0 (obviously), which leads to two clusters with one element on the first run, not meeting the criteria for a stable condition. i could fix that, but whats the point of "clustering" two points anyway?

**Comment by jd327** [comment]
Thanks for the quick reply @yetzt. The reason I opened this issue is two-fold:
1. Regardless of what the code does, it should never be stuck in an indefinite loop. It should either exit with some output, or throw an error.
2. I was excited about your code when I stumbled on it because it could solve a real-life scenario for our project. We have to display cities to the user in one of our features. In the middle of the process we calculate geographical coordinates - it might be 1 coordinate, or 2, or a million. Then we have to cluster them somehow (and we run thru this step regardless of how many coordinates we have for consistency - even if it's just one). In the end, and further down the process, we get one or several cities that can be displayed to the user.

That's why it's important for us that this clustering code works _consistently_ with _any number_ of data points. Do you think you could fix it so that it works with 1 or more geographical coordinates and doesn't get stuck?

**Comment by yetzt** [comment]
i have read up on the original implementation of s-means, and it indeed assigns an elment to a new cluster if the stddev-derived closest distance is 0, so i changed my code accordingly, which should fix your case.

**Comment by jd327** [comment]
Thank you @yetzt, seems to be working :]
As a sidenote, thanks for the repo overall! Saved me so much time...

**Comment by yetzt** [comment]
you're welcome :)
