### ISSUE TITLE
Geocluster does not return same object for same initial parameters

### ISSUE THREAD

**Issue by ioana-m** [yetzt/node-geocluster#4]
Hello,

I was hoping to use this library in order to create the clusters that I wanted on my map. But the problem is that with the same elements and bias the geocluster does not return the same set of clusters, I ran it many times and each time there were some differences. Then I noticed the you are using Math.random() to initialize the initial cluster map. Maybe this is the problem? Is there any way to solve this and get the same exact results for the same initial parameters?

Thank you.

**Comment by yetzt** [comment]
this is [by design ot the algorithm](https://github.com/c0bra/smeans.js/blob/master/src/smeans.js#L93). if you want redproducible results, s-means is not the algorithm you want.
