### ISSUE TITLE
#!/usr/bin/env node error

### ISSUE THREAD

**Issue by harrington101** [yetzt/node-geocluster#6]
The first line in the code reads "#!/usr/bin/env node" and it appears to be causing the code to crash in javascript es6.

**Comment by yetzt** [comment]
the first line is a [shebang](https://en.wikipedia.org/wiki/Shebang_(Unix)) and tells the shell what interpreter to use. works fine with node up to v14. can't reproduce any crashes. please be more specific.

**Comment by AdamGerthel** [comment]
It produces an error if used in browser: 
![Screenshot 2020-10-23 at 11 48 30](https://user-images.githubusercontent.com/1490370/96989226-af108200-1525-11eb-8e91-8349a1769628.png)

**Comment by yetzt** [comment]
it was never designed to be used in a browser. the file has a shebang. its meant to be used in a posix environment. a browser is not a posix environment. 

the code is public domain, it's trivial to copy it into whatever code you want to use in your browser and run it, without wrapping it in three layers of webpack to shoehorn the module.exports into the dom. 

won't fix.
